- hosts: localhost
  connection: local
  vars:
    vpc_subnet_id:
         - '{{ subnet1 }}'
         - '{{ subnet2 }}'
  tasks:
 
  - name: Gather EC2 facts.
    ec2_instance_facts:
      region: "{{ region }}"
      filters:
        "tag:backup": "yes"
        "tag:substack": "{{ stack }}"
    register: ec2_facts
  
  - name: Find snapshots.
    ec2_snapshot_facts:
      region: "{{ region }}"
      filters:
        "tag:identifier": "awsbackup"
        "tag:incremental": "{{ INCREMENTAL }}"
    register: ec2_snapshot_facts
  - name: Get ordered list of snapshots for stack.
    set_fact:
      snaps_fact_list:  "{{ ec2_snapshot_facts.snapshots|selectattr('tags.identifier', 'equalto', 'awsbackup')|selectattr('tags.incremental', 'equalto', INCREMENTAL)|selectattr('tags.instance', 'equalto', item.tags.substack)|sort(attribute='start_time')|reverse|map(attribute='snapshot_id')|list }}"
    with_items: "{{ ec2_facts.instances }}"
    register: snaps_fact_list_register 
  - name: Cut the list by our COUNT variable.
    set_fact:
      snaps_cut: "{{ item.ansible_facts['snaps_fact_list'][:1] }}"
    with_items: "{{ snaps_fact_list_register.results }}"
    register: snaps_cut_register
  - name: Find the latest snapshot of stack
    set_fact:
      snaps_joined: "{{ item.ansible_facts.snaps_cut }}"
    with_items: "{{ snaps_cut_register.results }}"
    register: snaps_joined_register
  
  - name: set fact the snapshot id
    set_fact:
      snaps_id: "{{ item }}"
    with_items: "{{ snaps_joined }}"
    register: snaps_joined_register_id
  - ec2_ami:
      region: "{{ region }}"
      name: "{{ snaps_id }}_{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}"
      state: present
      architecture: x86_64
      virtualization_type: hvm
      root_device_name: /dev/xvda
      device_mapping:
        - device_name: /dev/xvda
          snapshot_id: "{{ snaps_id }}"
          delete_on_termination: true
          volume_type: gp2
    register: image
 
  
    
      
  
  - name: Launch Instance
    ec2:
      group_id: "{{ ec2_sg_id }}"
      count: "{{ ec2_count }}"
      keypair: "{{ ec2_key_name }}"
      instance_type: "{{ ec2_instance_type }}"
      image: "{{ image.image_id }}"
      wait: true
      region: "{{ region }}"
      vpc_subnet_id: "{{item}}"
      monitoring: "{{ ec2_monitoring }}"
      assign_public_ip: "{{ ec2_assign_public_ip }}"
      instance_tags:
         Name: "{{ server }}"
         Application: "{{ server }}"
         Environment: "{{ env }}"
         Createdby: "{{ Creater }}"
         Expireyear: "{{ expday }}"
         substack: "{{ stack }}"
         Stack: Web
         Project: AWS
         requested_by: aws
    with_items: "{{vpc_subnet_id}}"     
    register: ec2

  - set_fact:
      instances: "{{ ec2.results }}"

  - name: Wait for SSH to come up
    local_action: wait_for
                  host={{ item.instances[0].private_ip }}
                  port="{{ PORT }}"
                  state=started
    with_items: "{{ instances }}"

  - name: Add dynamic host and variable
    add_host:
       name: "{{ item.instances[0].private_ip }}"
       groups: aws
       service: "{{ server }}"
       ansible_ssh_user: "{{ USER }}"
       ansible_ssh_pass: "{{ PASSWD }}"
       ansible_sudo_pass: "{{ PASSWD }}"
       ansible_ssh_port: "{{ PORT }}"
    with_items: "{{ instances }}"
     
- hosts: aws 
  become: yes
  become_user: root
  tasks:
    - include: "{{ path }}"
